# Generated by Django 2.2.14 on 2021-10-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211017_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='color_label',
        ),
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
    ]
