# Generated by Django 2.2.14 on 2021-10-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211017_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
