# Generated by Django 2.2.14 on 2021-10-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='title',
        ),
    ]
